version: "1.0"

services:
  api:
    build: ./api
    ports:
      - "3000:80"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=docker_api

  frontend:
    build: ./frontend
    ports:
      - "80:80"

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: docker_api
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
