version: "1.0"

services:
  api_back:
    build: ./api_back
    ports:
      - "3000:80"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=docker_api
    networks:
      - api_csv

  api_front:
    build: ./api_front
    ports:
      - "80:80"
    networks:
      - api_csv

  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: docker_api
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - api_csv

volumes:
  mysql_data:

networks:
  api_csv:
    driver: bridge
