name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies for API back
        working-directory: ./api_back
        run: npm install

      - name: Build and test API back
        working-directory: ./api_back
        run: npm start
