name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

  tests:
    runs-on: ubuntu-latest
    needs: validation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Test

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image for API back
        run: docker build -t myregistry/api_back:$GITHUB_SHA ./api_back

      - name: Build Docker image for API front
        run: docker build -t myregistry/api_back:$GITHUB_SHA ./api_front

      - name: Build Docker image for API db
        run: docker build -t myregistry/api_back:$GITHUB_SHA ./db

  deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Docker swarm
